// This file is automatically generated. Do not edit it directly.
import { createClient, type AuthChangeEvent, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

type AppSupabaseClient = SupabaseClient<Database>;

export class SupabaseConfigError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'SupabaseConfigError';
  }
}

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function getSupabaseUrl(): string | undefined {
  return import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
}

function getSupabasePublishableKey(): string | undefined {
  return import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;
}

export function isSupabaseConfigured(): boolean {
  return Boolean(getSupabaseUrl() && getSupabasePublishableKey());
}

function missingConfigMessage(): string {
  const missing = [
    ...(!getSupabaseUrl() ? ['SUPABASE_URL / VITE_SUPABASE_URL'] : []),
    ...(!getSupabasePublishableKey()
      ? ['SUPABASE_PUBLISHABLE_KEY / VITE_SUPABASE_PUBLISHABLE_KEY']
      : []),
  ];
  return `Missing Supabase environment variable(s): ${missing.join(', ')}. Set VITE_* vars at build time and SUPABASE_* vars at runtime in Cloudflare.`;
}

function createUnconfiguredClient(): AppSupabaseClient {
  const configError = () => new SupabaseConfigError(missingConfigMessage());
  const emptySession = { data: { session: null }, error: null as null };
  const emptyAuth = { data: { user: null, session: null }, error: configError() };

  return {
    auth: {
      getSession: () => Promise.resolve(emptySession),
      getUser: () => Promise.resolve({ data: { user: null }, error: configError() }),
      onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
      signInWithPassword: () => Promise.resolve(emptyAuth),
      signInWithOAuth: () => Promise.resolve({ data: { provider: "", url: "" }, error: configError() }),
      signUp: () => Promise.resolve(emptyAuth),
      signOut: () => Promise.resolve({ error: null }),
      updateUser: () => Promise.resolve({ data: { user: null }, error: configError() }),
      resetPasswordForEmail: () => Promise.resolve({ data: {}, error: configError() }),
    },
  } as unknown as AppSupabaseClient;
}

function createSupabaseClient(): AppSupabaseClient {
  const SUPABASE_URL = getSupabaseUrl();
  const SUPABASE_PUBLISHABLE_KEY = getSupabasePublishableKey();

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    return createUnconfiguredClient();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      flowType: 'pkce',
      detectSessionInUrl: true,
    },
  });
}

let _supabase: AppSupabaseClient | undefined;
let _warnedMissingConfig = false;

function getSupabaseClient() {
  if (!_supabase) {
    _supabase = createSupabaseClient();
    if (!isSupabaseConfigured() && !_warnedMissingConfig) {
      console.warn(`[Supabase] ${missingConfigMessage()}`);
      _warnedMissingConfig = true;
    }
  }
  return _supabase;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as AppSupabaseClient, {
  get(_, prop, receiver) {
    return Reflect.get(getSupabaseClient(), prop, receiver);
  },
});
